version: '3'

# Server + DB, for development
services:
  api-dev:
    container_name: api-dev
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      NODE_ENV: development
      PORT: 8000
      DB_URL: mongodb://db/
    volumes:
      - .:/usr/app

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data-dev:/data/db
    command: --quiet

volumes:
  data-dev:
