version: '3'

# Server for production
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod

    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_URL: xxxxx
    volumes:
      - .:/usr/app
