version: '3'

# MongoDB for development
services:
  mongodb:
    image: mongo
    container_name: mongo-dev
    restart: always
    networks:
      - dev-network
    volumes:
      - data-dev:/data/db
    ports:
      - '27017:27017'

networks:
  dev-network:
    driver: bridge

volumes:
  data-dev:




